import { Recipe } from './types';

export const SEED_RECIPES: Recipe[] = [
  { id: 'r1', name: 'Garlic Butter Pasta', cuisine: 'Italian', source: '@pastagrannies',
    ingredients: ['spaghetti', 'butter', 'garlic', 'parmesan', 'parsley', 'chili flakes'] },
  { id: 'r2', name: 'Lasagna Soup', cuisine: 'Italian', source: '@onepotwonders',
    ingredients: ['lasagna noodles', 'ground beef', 'crushed tomatoes', 'onion', 'garlic', 'ricotta', 'parmesan'] },
  { id: 'r3', name: 'Crispy Gnocchi', cuisine: 'Italian', source: '@feelgoodfoodie',
    ingredients: ['gnocchi', 'cherry tomatoes', 'burrata', 'basil', 'olive oil', 'garlic'] },
  { id: 'r4', name: 'Birria Tacos', cuisine: 'Mexican', source: '@tacosofinsta',
    ingredients: ['beef chuck', 'dried chiles', 'corn tortillas', 'onion', 'cilantro', 'oaxaca cheese', 'garlic'] },
  { id: 'r5', name: 'Elote Corn Salad', cuisine: 'Mexican', source: '@streetfoodlab',
    ingredients: ['corn', 'mayo', 'cotija', 'lime', 'cilantro', 'chili powder'] },
  { id: 'r6', name: 'Chicken Tinga Bowls', cuisine: 'Mexican', source: '@mealprepmania',
    ingredients: ['chicken thighs', 'chipotle in adobo', 'crushed tomatoes', 'onion', 'rice', 'lime', 'cilantro'] },
  { id: 'r7', name: 'Gochujang Chicken', cuisine: 'Asian', source: '@koreanfoodtok',
    ingredients: ['chicken thighs', 'gochujang', 'soy sauce', 'honey', 'garlic', 'ginger', 'sesame seeds'] },
  { id: 'r8', name: '15-min Garlic Noodles', cuisine: 'Asian', source: '@noodleworship',
    ingredients: ['ramen noodles', 'butter', 'garlic', 'soy sauce', 'brown sugar', 'scallions'] },
  { id: 'r9', name: 'Miso Salmon', cuisine: 'Asian', source: '@fishfridays',
    ingredients: ['salmon', 'miso paste', 'soy sauce', 'honey', 'ginger', 'rice'] },
  { id: 'r10', name: 'Thai Basil Beef', cuisine: 'Asian', source: '@wokthisway',
    ingredients: ['ground beef', 'thai basil', 'soy sauce', 'fish sauce', 'garlic', 'chili', 'rice'] },
  { id: 'r11', name: 'Smash Burgers', cuisine: 'Comfort', source: '@burgerscholar',
    ingredients: ['ground beef', 'american cheese', 'burger buns', 'onion', 'pickles', 'mayo'] },
  { id: 'r12', name: 'Buffalo Chicken Dip', cuisine: 'Comfort', source: '@gamedayeats',
    ingredients: ['chicken thighs', 'cream cheese', 'hot sauce', 'ranch', 'cheddar', 'scallions'] },
  { id: 'r13', name: 'Stovetop Mac & Cheese', cuisine: 'Comfort', source: '@cheesepull_king',
    ingredients: ['macaroni', 'cheddar', 'butter', 'milk', 'mustard powder'] },
  { id: 'r14', name: 'Green Goddess Salad', cuisine: 'Healthy', source: '@bakedbymelissa',
    ingredients: ['cabbage', 'cucumber', 'scallions', 'basil', 'lemon', 'olive oil', 'garlic'] },
  { id: 'r15', name: 'Salmon Rice Bowl', cuisine: 'Healthy', source: '@emilymariko',
    ingredients: ['salmon', 'rice', 'soy sauce', 'mayo', 'sriracha', 'avocado', 'nori'] },
  { id: 'r16', name: 'Chickpea Curry', cuisine: 'Healthy', source: '@plantyou',
    ingredients: ['chickpeas', 'coconut milk', 'curry powder', 'onion', 'garlic', 'ginger', 'spinach'] },
];
